// Generated by gencpp from file Uwb_Location/uwb.msg
// DO NOT EDIT!


#ifndef UWB_LOCATION_MESSAGE_UWB_H
#define UWB_LOCATION_MESSAGE_UWB_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Uwb_Location
{
template <class ContainerAllocator>
struct uwb_
{
  typedef uwb_<ContainerAllocator> Type;

  uwb_()
    : time()
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  uwb_(const ContainerAllocator& _alloc)
    : time()
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef ros::Time _time_type;
  _time_type time;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::Uwb_Location::uwb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Uwb_Location::uwb_<ContainerAllocator> const> ConstPtr;

}; // struct uwb_

typedef ::Uwb_Location::uwb_<std::allocator<void> > uwb;

typedef boost::shared_ptr< ::Uwb_Location::uwb > uwbPtr;
typedef boost::shared_ptr< ::Uwb_Location::uwb const> uwbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Uwb_Location::uwb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Uwb_Location::uwb_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Uwb_Location::uwb_<ContainerAllocator1> & lhs, const ::Uwb_Location::uwb_<ContainerAllocator2> & rhs)
{
  return lhs.time == rhs.time &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Uwb_Location::uwb_<ContainerAllocator1> & lhs, const ::Uwb_Location::uwb_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Uwb_Location

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::Uwb_Location::uwb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Uwb_Location::uwb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Uwb_Location::uwb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Uwb_Location::uwb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Uwb_Location::uwb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Uwb_Location::uwb_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Uwb_Location::uwb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "41573204035ba6cb84327d8f3ec13839";
  }

  static const char* value(const ::Uwb_Location::uwb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x41573204035ba6cbULL;
  static const uint64_t static_value2 = 0x84327d8f3ec13839ULL;
};

template<class ContainerAllocator>
struct DataType< ::Uwb_Location::uwb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Uwb_Location/uwb";
  }

  static const char* value(const ::Uwb_Location::uwb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Uwb_Location::uwb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time time\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::Uwb_Location::uwb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Uwb_Location::uwb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct uwb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Uwb_Location::uwb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Uwb_Location::uwb_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.time);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UWB_LOCATION_MESSAGE_UWB_H
